class_name SideQuestData
extends RefCounted
## Quêtes secondaires des personnages de l'histoire (deux par personnage) : la première s'ouvre après
## leur arc dans l'histoire, la seconde après la fin de l'histoire (contenu de fin de partie).
##
## Champs : id, npc, after (étape de l'histoire à avoir passée ; « fin » = histoire finie), title, text (journal),
## type : « item » (apporter item × n), « kill » (vaincre n monstres parmi `enemies`, n'importe où),
##        « boss » (vaincre n grandes bêtes de donjon), « tame » (apprivoiser n familiers),
##        « evolve » (faire évoluer n habitants par le nom), « have » (posséder un de ces objets : `items`) ;
## reward : {items: [[id, n]], xp, gold} ; start / end : pages de dialogue ; wait : ce qu'il dit en attendant.

const QUESTS := [
	# ---------------------------------------------------------------- Orvane
	{"id": "orvane_a", "npc": "orvane", "after": "orvane_2", "title": "Les graines du vieil arbre", "text": "Orvane veut replanter la forêt de sa jeunesse : apporte-lui 20 bûches et 10 fibres.",
		"type": "item", "item": "wood", "n": 20, "item2": "fiber", "n2": 10, "reward": {"items": [["larme_esprit", 1]], "xp": 80},
		"start": [["orvane", "Trois cents ans sans voir pousser un arbre... Apporte-moi du bois et des fibres, revenant. Je leur apprendrai à redevenir forêt."]],
		"wait": [["orvane", "Vingt bûches, dix fibres. Le bois se souvient de la forêt, les fibres de la terre."]],
		"end": [["orvane", "Regarde : les racines reprennent déjà. Tiens, une larme de mon ancien cristal. Je n'en ai plus besoin."]]},
	{"id": "orvane_b", "npc": "orvane", "after": "fin", "title": "Les cendres de Caël", "text": "Orvane veut purger la Brume qui reste : vaincs 3 grandes bêtes de donjon.",
		"type": "boss", "n": 3, "reward": {"items": [["orichalque", 1], ["cristal_aube", 1]], "xp": 600},
		"start": [["orvane", "La Brume de Caël s'est dispersée, mais des lambeaux se sont réfugiés dans les donjons. Les grandes bêtes s'en nourrissent encore."], ["orvane", "Abats-en trois, et le monde respirera enfin."]],
		"wait": [["orvane", "Trois grandes bêtes. Je sens encore la Brume dans leurs antres."]],
		"end": [["orvane", "C'est fini. Pour de bon, cette fois. Prends ce que Caël m'avait confié autrefois : de l'orichalque et un cristal d'aube."]]},
	# ---------------------------------------------------------------- Glou
	{"id": "glou_a", "npc": "glou", "after": "glou_2", "title": "Le grand festin de Glou", "text": "Glou veut goûter à tout : apporte-lui 5 ragoûts.",
		"type": "item", "item": "ragout", "n": 5, "reward": {"items": [["piece_or", 120]], "xp": 60},
		"start": [["glou", "Blup ! Glou a entendu parler du RAGOÛT. Glou veut du ragoût ! Cinq ragoûts ! Glou partage... un peu."]],
		"wait": [["glou", "Ragoût ? Ragoût ? ... Pas encore ragoût. Blup."]],
		"end": [["glou", "RAGOÛT ! Glou heureux ! Glou a trouvé ça dans son ventre, tiens. Pièces brillantes. Pas bonnes à manger."]]},
	{"id": "glou_b", "npc": "glou", "after": "fin", "title": "Glou veut évoluer", "text": "Glou veut devenir grand comme les autres : fais évoluer 2 habitants par le Pacte, pour lui montrer.",
		"type": "evolve", "n": 2, "reward": {"items": [["sang_demon", 1], ["larme_esprit", 2]], "xp": 400},
		"start": [["glou", "Pip est devenu grand. Les autres aussi. Glou veut voir comment on fait ! Montre à Glou ! Deux fois !"]],
		"wait": [["glou", "Nommer quelqu'un, et pouf, il grandit ! Glou veut voir ça encore."]],
		"end": [["glou", "Glou a compris ! Il faut des amis pour grandir. Glou a plein d'amis. Tiens, cadeaux trouvés dans des monstres. Glou les a pas mangés. Presque."]]},
	# ---------------------------------------------------------------- Grik
	{"id": "grik_a", "npc": "grik", "after": "grik_2", "title": "Les réserves de l'hiver", "text": "Grik veut remplir les greniers : apporte 20 bottes de blé.",
		"type": "item", "item": "ble", "n": 20, "reward": {"items": [["graines_ble", 20], ["piece_or", 80]], "xp": 90},
		"start": [["grik", "Les gobelins n'ont jamais eu de réserves. On mangeait ce qu'on trouvait. Cette année, je veux un grenier plein pour l'hiver !"]],
		"wait": [["grik", "Vingt bottes de blé. Les champs, la houe, les graines... Pip t'expliquera, il adore ça."]],
		"end": [["grik", "Un grenier plein ! Mon grand-père pleurerait de joie. Tiens, des graines de la meilleure récolte, et un peu d'or."]]},
	{"id": "grik_b", "npc": "grik", "after": "fin", "title": "Le conseil des anciens", "text": "Grik veut un village digne de la nation : rassemble 20 habitants.",
		"type": "have", "items": [], "pop": 20, "reward": {"items": [["lingot_or", 5], ["lingot_mithril", 2]], "xp": 500},
		"start": [["grik", "Une nation, c'est bien. Une nation peuplée, c'est mieux ! Vingt habitants, et je convoque le premier conseil des anciens."]],
		"wait": [["grik", "Il nous faut plus de monde. Recrute des voyageurs, construis des maisons !"]],
		"end": [["grik", "Vingt ! Le conseil des anciens est ouvert. Et comme doyen, je t'offre le trésor de la tribu. On l'a gardé trois générations."]]},
	# ---------------------------------------------------------------- Pip
	{"id": "pip_a", "npc": "pip", "after": "pip_eveil", "title": "La chasse du hobgobelin", "text": "Pip veut prouver sa nouvelle force : vaincs 8 loups ou sangliers avec lui.",
		"type": "kill", "enemies": ["loup", "loup_alpha", "loup_givre", "sanglier"], "n": 8, "reward": {"items": [["croc_meute", 1], ["leather", 10]], "xp": 150},
		"start": [["pip", "Je suis GRAND maintenant ! Allons chasser ! Huit bêtes, loups ou sangliers, et je raconterai ça à tout le village !"]],
		"wait": [["pip", "Encore ! Encore ! J'ai compté, il en manque !"]],
		"end": [["pip", "On est les meilleurs chasseurs du monde ! Tiens, j'ai taillé un croc pour toi, comme celui d'Ulric."]]},
	{"id": "pip_b", "npc": "pip", "after": "fin", "title": "Un ami à quatre pattes", "text": "Pip rêve d'un compagnon : apprivoise 2 familiers par le Pacte.",
		"type": "tame", "n": 2, "reward": {"items": [["ecaille_dragon", 2], ["piece_or", 200]], "xp": 400},
		"start": [["pip", "Tu as vu tes familiers ? Ils sont trop forts ! Moi aussi je veux apprendre. Montre-moi comment tu fais, deux fois !"]],
		"wait": [["pip", "Un monstre affaibli, E, et le Pacte ! C'est ça ? Montre-moi encore !"]],
		"end": [["pip", "J'ai tout noté ! Un jour, j'aurai mon propre loup. Tiens, des écailles que j'ai trouvées en éclaireur."]]},
	# ---------------------------------------------------------------- Ulric
	{"id": "ulric_a", "npc": "ulric", "after": "ulric", "title": "Les cerfs perdus", "text": "Ulric veut nourrir sa meute : apporte 10 viandes crues.",
		"type": "item", "item": "viande_crue", "n": 10, "reward": {"items": [["leather", 12], ["piece_or", 60]], "xp": 90},
		"start": [["ulric", "Les petits de la meute ont faim, et le gibier revient lentement. Dix viandes, Éveillé, et la meute s'en souviendra."]],
		"wait": [["ulric", "Dix viandes. La meute attend."]],
		"end": [["ulric", "La meute mange. Prends ces peaux, elles viennent des anciens chasseurs."]]},
	{"id": "ulric_b", "npc": "ulric", "after": "fin", "title": "Les loups de Brume", "text": "Des loups corrompus rôdent : vaincs 12 loups (gris, alpha ou givre).",
		"type": "kill", "enemies": ["loup", "loup_alpha", "loup_givre"], "n": 12, "reward": {"items": [["mithril_brut", 4], ["larme_esprit", 1]], "xp": 450},
		"start": [["ulric", "Certains loups ont bu la Brume. Ils ne sont plus des nôtres. Il faut les libérer. Douze, Éveillé. Cela me déchire, mais il le faut."]],
		"wait": [["ulric", "Il en reste. Je les entends hurler faux."]],
		"end": [["ulric", "Ils reposent en paix. Prends ce mithril, trouvé dans leurs tanières. Le Pacte des loups est éternel."]]},
	# ---------------------------------------------------------------- Maëlle
	{"id": "maelle_a", "npc": "maelle", "after": "maelle_2", "title": "La bibliothèque d'Émeraude", "text": "Maëlle veut classer ses notes : construis une bibliothèque.",
		"type": "room", "room": "bibliotheque", "reward": {"items": [["larme_esprit", 1], ["piece_or", 100]], "xp": 120},
		"start": [["maelle", "Mes notes s'empilent partout, même sous le lit de Glou. Il me faut une vraie bibliothèque. Des étagères, des pupitres..."]],
		"wait": [["maelle", "Une bibliothèque : pièce fermée avec des étagères. Je t'en serai éternellement reconnaissante."]],
		"end": [["maelle", "Parfait ! Tout est classé. J'ai même retrouvé une larme d'esprit entre deux pages. Elle est à toi."]]},
	{"id": "maelle_b", "npc": "maelle", "after": "fin", "title": "L'encyclopédie de l'Éveil", "text": "Maëlle écrit l'histoire des obélisques : éveille tous les obélisques du monde.",
		"type": "obelisks", "n": -1, "reward": {"items": [["cristal_aube", 1], ["lingot_mithril", 2]], "xp": 500},
		"start": [["maelle", "J'écris une encyclopédie. Mais il me manque des obélisques, ceux des contrées les plus lointaines. Tu veux bien les éveiller tous ?"]],
		"wait": [["maelle", "Il reste des pierres endormies. La carte (M) te les montre."]],
		"end": [["maelle", "Tous ! L'encyclopédie est complète. Tiens, un cristal d'aube : le réseau en a fait naître un quand le dernier obélisque s'est allumé."]]},
	# ---------------------------------------------------------------- Liora
	{"id": "liora_a", "npc": "liora", "after": "liora_pain", "title": "Des gâteaux pour les fées", "text": "Liora veut goûter aux gâteaux : apporte-lui 3 gâteaux.",
		"type": "item", "item": "gateau", "n": 3, "reward": {"items": [["larme_esprit", 2]], "xp": 100},
		"start": [["liora", "Le pain, c'est bien. Mais on m'a parlé du GÂTEAU. Avec des œufs, du lait, du blé... Trois, s'il te plaît !"]],
		"wait": [["liora", "Gâteau, gâteau, gâteau ! Trois !"]],
		"end": [["liora", "Mmmmh ! Les fées vont être jalouses. Tiens, deux larmes de fée, pour toi."]]},
	{"id": "liora_b", "npc": "liora", "after": "fin", "title": "Les fées sauvages", "text": "Des fées sauvages ont perdu la tête : ramène-les à la raison (vaincs 8 fées sauvages ou esprits follets).",
		"type": "kill", "enemies": ["fee_sauvage", "esprit_follet"], "n": 8, "reward": {"items": [["larme_esprit", 3], ["cristal_aube", 1]], "xp": 450},
		"start": [["liora", "Mes cousines sauvages ont respiré trop de Brume. Elles attaquent tout le monde ! Il faut les calmer. Un bon coup sur la tête, en général, ça marche."]],
		"wait": [["liora", "Il en reste ! Je les entends ricaner dans les bois."]],
		"end": [["liora", "Elles se sont réveillées, toutes confuses. Tiens : des larmes, et un petit cristal qu'elles gardaient."]]},
	# ---------------------------------------------------------------- Kaede
	{"id": "kaede_a", "npc": "kaede", "after": "kaede_3", "title": "L'entraînement des Cornes-Rouges", "text": "Kaede veut entraîner des gardes : construis un camp d'entraînement.",
		"type": "room", "room": "caserne", "reward": {"items": [["katana_cornes", 1]], "xp": 120},
		"start": [["kaede", "Le village a besoin de vraies lames. Construis-moi un camp d'entraînement, et je ferai de tes gardes des guerriers."]],
		"wait": [["kaede", "Deux mannequins, un râtelier. Je n'ai pas besoin de plus."]],
		"end": [["kaede", "Bien. Je vais les faire suer. J'ai forgé une seconde lame des Cornes-Rouges, pour ton meilleur garde. Ou pour toi."]]},
	{"id": "kaede_b", "npc": "kaede", "after": "fin", "title": "Les ogres de la montagne", "text": "Kaede veut venger les villages de montagne : vaincs 6 ogres ou orcs brutes.",
		"type": "kill", "enemies": ["ogre", "orc_brute"], "n": 6, "reward": {"items": [["sang_demon", 2], ["mithril_brut", 3]], "xp": 480},
		"start": [["kaede", "Des ogres pillent les villages des hauteurs, comme la bête avait pillé le mien. Pas cette fois. Six, et on rentre."]],
		"wait": [["kaede", "Ma lame n'a pas fini son travail."]],
		"end": [["kaede", "Les villages des hauteurs sont en sécurité. Merci, ami. Tiens, leur butin."]]},
	# ---------------------------------------------------------------- Kaïa
	{"id": "kaia_a", "npc": "kaia", "after": "kaia_3", "title": "Le courrier des nuages", "text": "Kaïa a perdu ses lettres : vaincs 6 harpies voleuses.",
		"type": "kill", "enemies": ["harpie"], "n": 6, "reward": {"items": [["cape_routes", 1], ["piece_or", 80]], "xp": 150},
		"start": [["kaia", "Des harpies sauvages m'ont volé tout mon courrier ! Les lettres d'amour de Borin, les factures de Lysandre... C'est une catastrophe !"]],
		"wait": [["kaia", "Elles volent dans les hauteurs, avec mon sac !"]],
		"end": [["kaia", "Tout le courrier ! Borin écrit des poèmes, tu savais ? Chut. Tiens, ma vieille cape de vol."]]},
	{"id": "kaia_b", "npc": "kaia", "after": "fin", "title": "La route des îles", "text": "Kaïa veut cartographier les îles : apporte-lui 3 perles des trésors du large.",
		"type": "item", "item": "perle", "n": 3, "reward": {"items": [["orichalque", 1]], "xp": 400},
		"start": [["kaia", "On raconte qu'il y a des îles au trésor au large ! Rapporte-moi trois perles de là-bas, je tracerai la carte des routes maritimes."]],
		"wait": [["kaia", "Trois perles, du large ! Une barque, et à l'aventure !"]],
		"end": [["kaia", "La carte est finie ! Et regarde ce qu'une mouette m'a apporté : un bout d'orichalque. Pour toi."]]},
	# ---------------------------------------------------------------- Borin
	{"id": "borin_a", "npc": "borin", "after": "borin_fer", "title": "Le premier lingot de mithril", "text": "Borin veut voir ton premier lingot de mithril (fondu au four).",
		"type": "item", "item": "lingot_mithril", "n": 2, "reward": {"items": [["mithril_brut", 6]], "xp": 150},
		"start": [["borin", "Tu as du mithril, maintenant. Mais sais-tu le fondre ? Apporte-moi deux lingots, et je jugerai ton travail."]],
		"wait": [["borin", "Deux lingots de mithril. Deux morceaux bruts par lingot, au four. Allez."]],
		"end": [["borin", "Hmph. Bons lingots. Presque dignes d'un nain. Tiens, du minerai de ma réserve personnelle. Ne le dis pas à Brunhild."]]},
	{"id": "borin_b", "npc": "borin", "after": "fin", "title": "Le chef-d'œuvre", "text": "Borin veut voir une arme légendaire : possède la Lame de l'Éveil, une lance ou une armure draconique.",
		"type": "have", "items": ["lame_eveil", "lance_draconique", "armure_draconique"], "reward": {"items": [["marteau_borin", 1], ["orichalque", 1]], "xp": 600},
		"start": [["borin", "Un vrai forgeron laisse un chef-d'œuvre derrière lui. Forge-toi une arme légendaire : la Lame de l'Éveil, ou quelque chose en écailles de dragon."]],
		"wait": [["borin", "Orichalque, écailles, cristaux... Le légendaire ne se fait pas en un jour."]],
		"end": [["borin", "... Par la barbe de mon grand-père. C'est magnifique. Tu es un forgeron, maintenant. Prends mon orichalque, j'en ai plus besoin que toi... non, en fait, prends-le."]]},
	# ---------------------------------------------------------------- Brunhild
	{"id": "brunhild_a", "npc": "brunhild", "after": "borin_fer", "title": "Les profondeurs de la mine", "text": "Brunhild veut nettoyer la mine : vaincs 8 araignées.",
		"type": "kill", "enemies": ["araignee"], "n": 8, "reward": {"items": [["lingot_or", 3], ["mithril_brut", 2]], "xp": 150},
		"start": [["brunhild", "Des araignées sont revenues dans les galeries profondes. Mes mineurs refusent d'y descendre. Huit, et on rouvre la mine."]],
		"wait": [["brunhild", "Il en reste. Mes mineurs entendent leurs pattes."]],
		"end": [["brunhild", "La mine est rouverte. Voici ta part de la première extraction."]]},
	{"id": "brunhild_b", "npc": "brunhild", "after": "fin", "title": "Le trône sous la montagne", "text": "Brunhild veut un marbre digne de son trône : apporte 20 blocs de marbre.",
		"type": "item", "item": "bloc_marbre", "n": 20, "reward": {"items": [["orichalque", 1], ["lingot_or", 5]], "xp": 450},
		"start": [["brunhild", "Mon trône est en granit. Du granit ! Il me faut du marbre, vingt blocs, et je te paierai comme une reine."]],
		"wait": [["brunhild", "Vingt blocs de marbre. Le marbre brut se trouve sur la roche, avec une pioche en fer."]],
		"end": [["brunhild", "Magnifique. Comme promis : paiement royal. Et un morceau d'orichalque du trésor de mes ancêtres."]]},
	# ---------------------------------------------------------------- Lysandre
	{"id": "lysandre_a", "npc": "lysandre", "after": "lysandre_secret", "title": "Racheter sa dette", "text": "Lysandre veut se racheter : apporte-lui 3 lingots d'or pour rembourser ses victimes.",
		"type": "item", "item": "lingot_or", "n": 3, "reward": {"items": [["perle", 5], ["piece_or", 250]], "xp": 150},
		"start": [["lysandre", "J'ai vendu des secrets à Morvain. Des gens ont souffert. Je veux rembourser chacun d'eux... mais j'ai tout dépensé. Aide-moi : trois lingots d'or."]],
		"wait": [["lysandre", "Trois lingots. Je te rendrai tout, promis. Avec intérêts, même. Enfin, un peu."]],
		"end": [["lysandre", "C'est fait. Tout le monde est remboursé. Et moi, je dors mieux. Tiens, mes perles, et plus que ce que tu m'as donné."]]},
	{"id": "lysandre_b", "npc": "lysandre", "after": "fin", "title": "Le grand bazar", "text": "Lysandre veut un vrai marché : construis 2 marchés.",
		"type": "room", "room": "marche", "count": 2, "reward": {"items": [["piece_or", 600], ["sang_demon", 1]], "xp": 450},
		"start": [["lysandre", "Une nation a besoin d'un grand bazar. Deux marchés, et j'y ferai venir des marchands du bout du monde !"]],
		"wait": [["lysandre", "Deux marchés, héros. Des étals, du monde, du bruit !"]],
		"end": [["lysandre", "Écoute ce bruit ! C'est le son de l'or. Voici ta part, et un flacon rare que m'a vendu un marchand démon. Ne pose pas de questions."]]},
	# ---------------------------------------------------------------- Zzar
	{"id": "zzar_a", "npc": "zzar", "after": "zzar_2", "title": "La gelée royale", "text": "Zzar veut échanger : apporte 10 baies et 5 laitages (lait).",
		"type": "item", "item": "baies", "n": 10, "item2": "lait", "n2": 5, "reward": {"items": [["ecaille_dragon", 2]], "xp": 120},
		"start": [["zzar", "Zzz. La Ruche veut goûter les nourritures des mammifères. Dix baies, cinq laits. La Ruche paiera."]],
		"wait": [["zzar", "Zzz. Baies. Lait. La Ruche attend."]],
		"end": [["zzar", "Zzz... intéressant. La Ruche approuve le lait. Voici des écailles, trouvées dans le sable."]]},
	{"id": "zzar_b", "npc": "zzar", "after": "fin", "title": "L'empereur des sables", "text": "Zzar veut la fin des scorpions : vaincs 10 scorpions.",
		"type": "kill", "enemies": ["scorpion"], "n": 10, "reward": {"items": [["ecaille_dragon", 4], ["sang_demon", 1]], "xp": 450},
		"start": [["zzar", "Zzz. Les scorpions reviennent, plus gros, plus nombreux. La Ruche veut qu'ils disparaissent. Dix."]],
		"wait": [["zzar", "Zzz. La Ruche compte encore des scorpions."]],
		"end": [["zzar", "Zzz. Le désert est calme. La Ruche offre ses trésors au mammifère. Le mammifère est... apprécié."]]},
	# ---------------------------------------------------------------- Gorvak
	{"id": "gorvak_a", "npc": "gorvak", "after": "gorvak_ble", "title": "Les champs de la Horde", "text": "Gorvak veut des outils pour ses fermiers : apporte 3 houes.",
		"type": "item", "item": "houe", "n": 3, "reward": {"items": [["hache_horde", 1]], "xp": 120},
		"start": [["gorvak", "Mes orcs labourent avec leurs haches. Ça marche mal. Trois houes, et on fera pousser plus de blé que tout le royaume."]],
		"wait": [["gorvak", "Trois houes. Deux bouts de bois, deux pierres. Même un orc sait faire. Enfin, presque."]],
		"end": [["gorvak", "Les champs sont magnifiques. Prends la hache de mon père : on n'en a plus besoin pour labourer."]]},
	{"id": "gorvak_b", "npc": "gorvak", "after": "fin", "title": "Les pillards d'hier", "text": "Des gobelins pillards refusent la paix : vaincs 10 gobelins pillards ou orcs brutes.",
		"type": "kill", "enemies": ["gobelin_pillard", "orc_brute"], "n": 10, "reward": {"items": [["mithril_brut", 4], ["lingot_or", 3]], "xp": 450},
		"start": [["gorvak", "Certains de mes anciens frères pillent encore. Ils disent que je suis devenu un fermier. C'est vrai. Mais je sais encore me battre. Aide-moi."]],
		"wait": [["gorvak", "Ils sont encore là, à piller les fermes des autres."]],
		"end": [["gorvak", "Les survivants ont demandé à rejoindre nos champs. La paix, ça se gagne aussi. Tiens, leur butin."]]},
	# ---------------------------------------------------------------- Sylve
	{"id": "sylve_a", "npc": "sylve", "after": "sylve", "title": "Le jardin des dryades", "text": "Sylve veut un jardin : apporte 10 carottes et 10 pommes de terre.",
		"type": "item", "item": "carotte", "n": 10, "item2": "pomme_de_terre", "n2": 10, "reward": {"items": [["larme_esprit", 2]], "xp": 120},
		"start": [["sylve", "Les arbres aiment les jardins. Apporte-moi des carottes et des pommes de terre, je les planterai au pied des chênes."]],
		"wait": [["sylve", "Dix carottes, dix pommes de terre. La terre attend."]],
		"end": [["sylve", "La terre est heureuse. Voici deux larmes des arbres, cueillies au lever du soleil."]]},
	{"id": "sylve_b", "npc": "sylve", "after": "fin", "title": "Les dryades corrompues", "text": "Sylve veut sauver ses sœurs : vaincs 6 dryades corrompues.",
		"type": "kill", "enemies": ["dryade_corrompue"], "n": 6, "reward": {"items": [["larme_esprit", 3], ["cristal_aube", 1]], "xp": 480},
		"start": [["sylve", "Mes sœurs du bois enchanté ont bu la Brume. Elles souffrent. Libère-les, je t'en prie."]],
		"wait": [["sylve", "Elles pleurent encore dans les bois."]],
		"end": [["sylve", "Elles dorment enfin. Les arbres te remercient. Prends ceci, c'est leur dernier présent."]]},
	# ---------------------------------------------------------------- Aldéric
	{"id": "alderic_a", "npc": "alderic", "after": "alderic_2", "title": "L'honneur des chevaliers", "text": "Aldéric veut rééquiper l'ordre : apporte 2 armures de fer et 2 boucliers de fer.",
		"type": "item", "item": "iron_armor", "n": 2, "item2": "shield_iron", "n2": 2, "reward": {"items": [["bouclier_hauterive", 1]], "xp": 150},
		"start": [["alderic", "Mon ordre renaît, avec des volontaires de tous les peuples. Il leur faut des armures. Deux armures, deux boucliers, pour commencer."]],
		"wait": [["alderic", "Deux armures de fer, deux boucliers. L'enclume est ton amie."]],
		"end": [["alderic", "Le nouvel ordre de l'Aube a ses premiers chevaliers : un gobelin, un orc et une naine. Le roi va faire une tête. Tiens, un bouclier d'Hauterive."]]},
	{"id": "alderic_b", "npc": "alderic", "after": "fin", "title": "Les derniers templiers", "text": "Des templiers morts-vivants hantent les ruines : vaincs 10 squelettes.",
		"type": "kill", "enemies": ["squelette", "seigneur_squelette"], "n": 10, "reward": {"items": [["fragment_brume", 4], ["orichalque", 1]], "xp": 480},
		"start": [["alderic", "Des templiers de Morvain errent encore dans les ruines, morts mais debout. Mes anciens frères, peut-être. Il faut les laisser reposer."]],
		"wait": [["alderic", "Il en reste. J'entends leurs armures grincer la nuit."]],
		"end": [["alderic", "Ils reposent. Merci, Éveillé. Voici ce qu'ils gardaient, dans la crypte."]]},
	# ---------------------------------------------------------------- Edmond
	{"id": "edmond_a", "npc": "edmond", "after": "traite", "title": "Le tribut de l'amitié", "text": "Edmond veut une route pavée entre vos pays : apporte 30 blocs de pierre polie.",
		"type": "item", "item": "bloc_pierre_polie", "n": 30, "reward": {"items": [["lingot_or", 4], ["piece_or", 200]], "xp": 150},
		"start": [["edmond", "Une route pavée entre Hauterive et ta nation ! Les marchands en rêvent. Il me faut de la pierre polie, trente blocs."]],
		"wait": [["edmond", "Trente blocs de pierre polie, mon ami. La route attend."]],
		"end": [["edmond", "La route royale est inaugurée ! Le commerce va exploser. Voici le paiement de la couronne."]]},
	{"id": "edmond_b", "npc": "edmond", "after": "fin", "title": "La paix des royaumes", "text": "Edmond veut une ambassade : construis une salle du trône et une taverne.",
		"type": "room", "room": "taverne", "reward": {"items": [["couronne_pactes", 1], ["piece_or", 500]], "xp": 500},
		"start": [["edmond", "Une ambassade a besoin d'un lieu où l'on boit ensemble. Construis une taverne, et Hauterive y enverra son ambassadeur."]],
		"wait": [["edmond", "Une taverne. Des tables, des tonneaux, et de la bonne humeur."]],
		"end": [["edmond", "L'ambassadeur est ravi : il a déjà perdu trois parties de dés contre Glou. Voici un présent de la couronne."]]},
	# ---------------------------------------------------------------- Séléné
	{"id": "selene_a", "npc": "selene", "after": "selene_2", "title": "Les roses de minuit", "text": "Séléné veut des fleurs pour la tombe de Caël : apporte 10 fibres et 5 lanternes.",
		"type": "item", "item": "fiber", "n": 10, "item2": "lanterne", "n2": 5, "reward": {"items": [["sang_demon", 2]], "xp": 150},
		"start": [["selene", "Je veux lui faire un jardin de lumière. Des fibres pour tresser des couronnes, et des lanternes pour que la nuit ne soit plus jamais noire."]],
		"wait": [["selene", "Dix fibres, cinq lanternes. Je sais, c'est sentimental. Tais-toi."]],
		"end": [["selene", "C'est beau. Il aurait aimé. Tiens, un flacon de ma réserve. Ne demande pas d'où il vient."]]},
	{"id": "selene_b", "npc": "selene", "after": "fin", "title": "Les démons de la nuit", "text": "Des démons profitent de la chute de Caël : vaincs 8 démons.",
		"type": "kill", "enemies": ["demon", "seigneur_demon"], "n": 8, "reward": {"items": [["sang_demon", 3], ["orichalque", 1]], "xp": 500},
		"start": [["selene", "Les démons que Caël tenait en laisse sont libres. Ils chassent sur mes terres. Chassons-les ensemble, petit Éveillé."]],
		"wait": [["selene", "Il en reste. La nuit en est pleine."]],
		"end": [["selene", "Mes terres sont calmes. Merci. Prends ceci, arraché au plus vieux d'entre eux."]]},
	# ---------------------------------------------------------------- Vharok
	{"id": "vharok_a", "npc": "vharok", "after": "vharok_2", "title": "La chaleur de l'œuf", "text": "Vharok veut garder l'œuf au chaud : apporte 20 bûches et 5 torches.",
		"type": "item", "item": "wood", "n": 20, "item2": "torche", "n2": 5, "reward": {"items": [["ecaille_dragon", 4]], "xp": 150},
		"start": [["vharok", "L'œuf est tiède, mais pas assez. Il lui faut un feu éternel. Du bois et des torches, sang-chaud."]],
		"wait": [["vharok", "Vingt bûches, cinq torches. Vite, il refroidit."]],
		"end": [["vharok", "Il est chaud. Il bouge, même. Prends ces écailles : ce sont celles de sa mère."]]},
	{"id": "vharok_b", "npc": "vharok", "after": "fin", "title": "Les salamandres ardentes", "text": "Vharok veut protéger le nid : vaincs 8 salamandres ou slimes de magma.",
		"type": "kill", "enemies": ["salamandre", "slime_magma"], "n": 8, "reward": {"items": [["ecaille_dragon", 6], ["orichalque", 1]], "xp": 500},
		"start": [["vharok", "Des salamandres rôdent autour du nid, attirées par sa chaleur. Elles mangeraient l'œuf. Abats-les."]],
		"wait": [["vharok", "Il en reste. Le nid tremble."]],
		"end": [["vharok", "L'œuf a éclos. Un petit dragon, sang-chaud. Le premier depuis trois siècles. Il porte ton odeur. Prends ce trésor du nid."]]},
	# ---------------------------------------------------------------- Aurèle
	{"id": "aurele_a", "npc": "aurele", "after": "aurele_2", "title": "Les prières du Ciel", "text": "Aurèle veut un temple digne : construis un second temple.",
		"type": "room", "room": "temple", "count": 2, "reward": {"items": [["larme_esprit", 3]], "xp": 200},
		"start": [["aurele", "Le Ciel observe ta nation. Un second temple lui montrerait que les peuples prient ensemble."]],
		"wait": [["aurele", "Un autel, deux bougeoirs, une pièce fermée. Le Ciel est patient."]],
		"end": [["aurele", "Le Ciel est satisfait. Il m'autorise à rester parmi vous. Prends ces larmes, bénies."]]},
	{"id": "aurele_b", "npc": "aurele", "after": "fin", "title": "L'épreuve des cieux", "text": "Aurèle veut mesurer ta puissance : atteins le niveau 30.",
		"type": "level", "n": 30, "reward": {"items": [["cristal_aube", 2], ["orichalque", 1]], "xp": 800},
		"start": [["aurele", "Tu as vaincu Caël. Mais es-tu prêt pour ce qui viendra ? Deviens plus fort encore. Niveau trente, Éveillé."]],
		"wait": [["aurele", "Continue de grandir. Le Ciel t'observe."]],
		"end": [["aurele", "Tu es digne d'un séraphin. Voici les dernières lumières du premier Cœur."]]},
]
