class_name StoryDialogs
extends RefCounted
## Dialogues de l'histoire principale : identifiant -> {pages: [[qui, texte], ...], choices: [[texte, clé], ...]}.
## « hero » = le héros ; {hero} est remplacé par son nom. « wait_<étape> » : quand l'objectif n'est pas rempli ;
## « <personnage>_idle » : ce qu'il dit le reste du temps.

const DIALOGS := {
	# ================================================================ ACTE I — Une autre vie
	"intro": {"pages": [
		["orvane", "... Tu m'entends ? Non, ne cherche pas autour de toi. Ici. Dans le cristal."],
		["hero", "Un cristal qui parle... J'ai dû me cogner la tête plus fort que je ne pensais."],
		["orvane", "Ha ! Trois cents ans que personne ne m'entend, et le premier qui y parvient me prend pour une bosse. Je suis Orvane, l'Ancien des Racines."],
		["orvane", "Et toi, tu n'es pas d'ici. Ton âme a une odeur étrange... de pluie sur du métal, de lumières qui ne s'éteignent jamais."],
		["hero", "Je me souviens... d'une ville immense, de tours de verre. D'une vie à courir sans jamais arriver nulle part. Puis un soir de pluie, des phares, un choc. Et le silence."],
		["orvane", "Alors tu es mort là-bas, et tu as renaît ici. Ça arrive, parfois. Les âmes qui s'éteignent trop tôt traversent le voile. Seules ces âmes-là peuvent m'entendre."],
		["orvane", "Moi, on m'a enchaîné dans cette pierre le jour où le Cœur d'Aube a été brisé. Depuis, je regarde le monde s'assombrir sans pouvoir bouger une feuille."],
		["orvane", "Mais assez parlé de moi. Tu vois cette petite chose qui tremble derrière le cristal ? Elle me tient compagnie depuis des années. Elle a peur de toi. Va lui dire bonjour."],
	], "choices": [["« D'accord, Orvane. »", "ok"], ["« Pourquoi devrais-je t'écouter ? »", "doute"]]},
	"glou": {"pages": [
		["glou", "Blup ! ... Blup blup ?"],
		["hero", "Salut, toi. Je ne vais pas te faire de mal."],
		["glou", "... Toi... parler ? Glou comprendre toi ! Personne comprendre Glou, jamais. Seulement le caillou qui parle."],
		["orvane", "C'est un slime, un tout petit. Il mange tout ce qui traîne, même les cailloux. Surtout les cailloux, en fait."],
		["glou", "Glou pas manger caillou-qui-parle ! Glou gentil. Glou... ami ?"],
		["orvane", "Bien. Maintenant, un service : réveille deux obélisques pour moi. Leur lumière ronge mes chaînes. Glou restera ici à surveiller que je ne m'envole pas. Ha !"],
	]},
	"orvane_2": {"pages": [
		["orvane", "Je l'ai senti ! Deux lumières, et mes chaînes ont gémi. Tu as de la ressource, pour un revenant."],
		["hero", "Les pierres se sont allumées dès que je me suis approché. Comme si elles me reconnaissaient."],
		["orvane", "Elles reconnaissent ton âme. Une âme venue d'ailleurs est plus vaste que les nôtres : elle peut porter la confiance de tout un peuple. C'est ce qu'on appelait jadis un Pacte."],
		["orvane", "Quand un peuple te confie son destin et que tu lui confies le tien, vous grandissez ensemble. Vous changez, même. Les anciens rois n'avaient pas d'autre pouvoir."],
		["orvane", "Faisons un pacte, toi et moi : tu briseras mes chaînes, et je t'apprendrai tout ce que je sais de ce monde. Marché conclu ?"],
		["hero", "Marché conclu."],
		["orvane", "Ahh... Tu sens ? Ta Voix d'Outre-Monde s'éveille. Tu apprendras plus vite que n'importe qui ici. Ouvre ton arbre de talents (T) : la branche du Pacte t'appartient désormais."],
		["orvane", "Oh, et Glou a faim. Glou a toujours faim. Apporte-lui quelques baies, tu verras."],
	]},
	"glou_2": {"pages": [
		["glou", "BAIES ! Baies baies baies ! ... Glou mange tout !"],
		["hero", "Doucement, doucement... Attends, tu brilles ?"],
		["glou", "Glou mange, Glou devient fort ! Glou mange monstre, Glou devient TRÈS fort ! Toi aussi, toi aussi ! Glou partage !"],
		["orvane", "Par mes racines... Il vient de te transmettre son don. Un slime qui fait un pacte, je n'avais jamais vu ça. Tu pourras dévorer un peu de la force de ceux que tu vaincs."],
		["glou", "Glou va au village ! Glou garde la cuisine ! ... Glou mange PAS toute la cuisine. Promis. Un peu seulement."],
		["orvane", "Maintenant, écoute : dans les bois, une tribu de gobelins tremble de peur. Je sens leur angoisse d'ici, elle me chatouille les racines. Va les voir."],
	]},
	"wait_glou_2": {"pages": [["glou", "Glou a faim... Cinq baies ! Les buissons, là-bas, pleins de baies ! Blup."]]},
	# ================================================================ ACTE II — Les gobelins et le loup
	"grik": {"pages": [
		["grik", "N-ne t'approche pas ! Nous n'avons rien ! Plus de viande, plus de baies, plus rien !"],
		["hero", "Je ne suis pas venu vous voler. Un ami m'a dit que vous aviez besoin d'aide."],
		["grik", "De l'aide ? Pour des gobelins ? Personne n'aide les gobelins... Pardonne-moi, je suis Grik, l'ancien de la tribu. Le seul qui reste debout, avec mes vieilles jambes."],
		["grik", "Une meute de loups nous traque depuis trois lunes. Chaque nuit, elle emporte l'un des nôtres. Nos jeunes n'osent plus sortir chercher à manger."],
		["grik", "Sauf Pip. Ce petit fou connaît leurs pistes mieux que personne. Parle-lui avant d'y aller."],
	]},
	"pip": {"pages": [
		["pip", "T'es le géant qui parle aux cailloux ? Grik dit que t'es un héros. T'as pas l'air d'un héros. T'as l'air perdu."],
		["hero", "Un peu des deux, sans doute. Tu connais les loups ?"],
		["pip", "Je les suis tous les jours ! Ils sont six, et ils ont un chef énorme, gris, avec des yeux qui brillent. Mais c'est bizarre..."],
		["pip", "Ils mangent pas les gobelins qu'ils emportent. Ils les laissent au bord de la rivière, tout tremblants. Comme s'ils voulaient juste qu'on parte."],
		["pip", "Grik dit que je raconte n'importe quoi. Chasse-les, toi. Et si tu vois leur chef... regarde-le bien, d'accord ?"],
	]},
	"wait_loups": {"pages": [["pip", "Ils rôdent encore autour du camp ! Six, je te dis. J'ai compté deux fois."]]},
	"ulric": {"pages": [
		["ulric", "Assez. Tu as abattu ma meute. Regarde-moi, humain... ou quoi que tu sois."],
		["hero", "Un loup qui parle ? Pip avait raison, tu n'es pas un loup comme les autres."],
		["ulric", "Je suis Ulric, seigneur de la meute des Bois-Gris. Nous ne chassions pas les gobelins pour les manger. Nous voulions qu'ils partent."],
		["ulric", "La Brume a vidé nos forêts. Plus de cerfs, plus de lièvres. Nos petits meurent de faim. Il fallait les terres de chasse des gobelins, ou mourir."],
		["ulric", "J'ai perdu. Tue-moi si tu veux. Ou alors... on raconte que tu fais des pactes. Un loup peut-il faire un pacte ?"],
		["hero", "Si les gobelins acceptent, oui. Il y a de la place pour tout le monde, si on chasse ensemble au lieu de se chasser."],
		["ulric", "... Ensemble. Soit. Prends ce croc, il vient de mon père. Et prends mon hurlement : quand tu hurleras, la meute hurlera avec toi, où qu'elle soit."],
	]},
	"grik_2": {"pages": [
		["grik", "La meute... elle est partie ! Et Pip dit que tu as parlé avec leur chef, et qu'il va nous apprendre à chasser le cerf ! C'est vrai ?!"],
		["grik", "Tu as une étrange lumière autour de toi, étranger. Mon grand-père parlait de ceux qui portent un Pacte. Je pensais que c'étaient des contes pour endormir les petits."],
		["hero", "Ce n'est pas un conte. Si ta tribu le veut, nous pouvons faire un pacte, et vivre ensemble."],
		["grik", "Ensemble... Dans un vrai village, avec des murs et des lits ? Ou bien restons-nous libres dans nos bois, mais alliés à toi pour toujours ?"],
	], "choices": [["« Venez vivre au village. »", "pacte"], ["« Restez libres, soyons alliés. »", "allies"]]},
	# ================================================================ ACTE III — L'érudite et la fée
	"maelle": {"pages": [
		["maelle", "Pardon... C'est bien ici, le village où des gobelins dorment dans des lits et où un slime tient la cuisine ? Je croyais à une rumeur d'auberge."],
		["hero", "C'est bien ici. Et on ne mord personne, promis. Sauf Glou, parfois."],
		["maelle", "Je m'appelle Maëlle, érudite de la forêt d'Émeraude. J'étudie les obélisques, ces pierres qui veillent sur chaque contrée. Jadis, une seule source les nourrissait : le Cœur d'Aube."],
		["maelle", "Il a été brisé il y a trois siècles par le Seigneur de la Brume. Ses éclats ont été avalés par les grandes bêtes des régions, et depuis, la Brume ronge le royaume."],
		["maelle", "Mais ici, les obélisques s'allument à nouveau. Et on raconte que c'est toi qui les réveilles. Les anciens textes parlent d'un « Éveillé »..."],
		["hero", "Il y a un esprit, Orvane, enchaîné dans un cristal près d'ici. Il dit que mon âme vient d'ailleurs."],
		["maelle", "Orvane ?! L'Ancien des Racines ? Il existe vraiment ? ... Il faut que j'en sache plus. Éveille d'autres obélisques, je veux mesurer leur lumière."],
	]},
	"liora": {"pages": [
		["liora", "Hi hi ! Un grand ! Un grand qui fait briller les pierres ! Je t'ai vu, je t'ai vu, je te suis depuis trois jours !"],
		["hero", "Depuis trois jours ? Je n'ai rien remarqué."],
		["liora", "Évidemment. Je suis Liora, fée des pierres. Quand j'étais toute petite, toutes les pierres brillaient, et les fées dansaient dessus la nuit. C'était le bon temps."],
		["liora", "Je sais des choses sur le Cœur d'Aube que ton érudite ne sait pas. Des choses importantes ! Mais... une fée ne parle jamais le ventre vide."],
		["liora", "Du pain. Trois pains tout chauds. Les humains ont inventé beaucoup de bêtises, mais le pain, c'est leur chef-d'œuvre."],
	]},
	"wait_liora_pain": {"pages": [["liora", "Trois pains ! Tout chauds ! Blé, meule, pétrin, four... Tu as l'air de quelqu'un qui sait faire du pain. Si, si."]]},
	"liora_pain": {"pages": [
		["liora", "Mmmh... Ça sent la maison. D'accord, d'accord, un marché est un marché."],
		["liora", "Écoute bien : le Cœur n'a pas été brisé par hasard. Quelqu'un l'a brisé EXPRÈS, de l'intérieur. Les fées l'ont vu. Une lumière qui se déchirait en deux, comme un cœur qui pleure."],
		["liora", "Et la Brume n'est pas venue d'ailleurs. Elle est sortie du Cœur, au même moment. Comme si... comme si la lumière avait une ombre."],
		["hero", "Qui aurait fait ça ?"],
		["liora", "Ça, les fées ne l'ont pas vu. Mais tiens : deux larmes d'esprit, et un peu de mes yeux de fée. Tu verras les failles de tes ennemis comme nous voyons les failles des pierres."],
	]},
	"maelle_2": {"pages": [
		["maelle", "Brisé de l'intérieur ? Et la Brume sortie du Cœur lui-même ? ... Ça contredit tous mes livres. Ou alors, mes livres mentent."],
		["maelle", "Regarde mes notes : la lumière des obélisques forme un réseau, comme les veines d'une feuille. Et toutes ces veines convergent vers un seul point, le Sanctuaire de l'Éveil."],
		["maelle", "Si on rassemble les éclats, le réseau renaîtra et la Brume reculera. Mais les éclats sont dans le ventre des grandes bêtes, et nous sommes un village de gobelins et de débutants."],
		["maelle", "En venant, j'ai croisé une guerrière oni dans les hauteurs. Blessée, seule, et d'une colère... Elle a failli me couper en deux. Tu devrais aller la voir. Prudemment."],
	]},
	# ================================================================ ACTE IV — La dernière lame oni
	"kaede": {"pages": [
		["kaede", "Un pas de plus et ta tête roule dans la neige. Tu sens le gobelin, l'elfe, le loup et... autre chose. Qu'es-tu ?"],
		["hero", "Un voisin. Je construis un village où tout le monde a sa place. Maëlle m'a parlé de toi."],
		["kaede", "L'elfe bavarde. Hmph. Je suis Kaede, fille du clan des Cornes-Rouges. La dernière du clan, depuis la nuit où la bête est sortie du donjon."],
		["kaede", "Elle a dévoré nos forges, nos maisons, mon père. Mon frère Ren a disparu en la poursuivant. J'ai juré sur ma lame de la tuer, mais seule, je n'y arrive pas."],
		["kaede", "Si tu veux ma confiance, descends dans ce donjon et abats la bête. Alors seulement, je t'écouterai."],
	]},
	"wait_kaede_bete": {"pages": [["kaede", "La bête vit encore. Je le sens dans mes os. Son donjon est tout près : carré rouge sur ta carte."]]},
	"duel_ren": {"pages": [
		["ren", "... Tu as tué la bête. Elle m'appartenait. ELLE ÉTAIT À MOI."],
		["hero", "Ces cornes rouges... Tu es Ren ? Le frère de Kaede ? Elle te croit mort !"],
		["ren", "Ren est mort dans la Brume. Il ne reste que la faim. Et une voix... une voix douce qui promet que la douleur s'arrête si je te tue."],
		["ren", "Un homme en robe blanche m'a donné ce cristal noir. « Pour venger ton clan », a-t-il dit. Il avait raison. Je n'ai plus mal. Je n'ai plus RIEN."],
		["hero", "Ren, écoute-moi ! Ta sœur est à quelques pas d'ici !"],
		["ren", "ALORS ELLE ME REGARDERA TE DÉVORER !"],
	]},
	"kaede_2": {"pages": [
		["kaede", "... Ren. C'était Ren. Je l'ai vu tomber de loin. J'ai reconnu sa façon de tenir la lame."],
		["kaede", "Avant de mourir, il a souri. Pour la première fois depuis des années. Il a dit « Merci, grande sœur ». Et le cristal noir s'est brisé dans sa main."],
		["hero", "Il a parlé d'un homme en robe blanche. Quelqu'un lui a donné ce cristal pour qu'il devienne... ça."],
		["kaede", "Une robe blanche... avec un soleil brodé ? J'ai vu ce symbole sur les pierres du donjon. Je croyais que c'était une vieille ruine."],
		["kaede", "Quelqu'un a fait ça à mon frère. Et je le trouverai. Mais d'abord... chez nous, un guerrier ne part pas dans la terre. Il part dans les flammes."],
	]},
	"wait_kaede_3": {"pages": [["kaede", "Dix bûches. Pour que les flammes montent assez haut pour qu'il retrouve notre père. C'est tout ce que je te demande."]]},
	"kaede_3": {"pages": [
		["kaede", "... Les flammes sont hautes. Il aurait aimé. Il disait toujours que j'étais trop lente pour le rattraper."],
		["kaede", "Tiens. La Lame des Cornes-Rouges. C'était celle de Ren. Elle doit servir à quelque chose, et entre mes mains, elle ne servirait qu'à la vengeance."],
		["kaede", "Et prends aussi la Ruée écarlate, l'art secret de notre clan. Je te l'apprends parce que tu as rendu la paix à mon frère."],
		["kaede", "Maintenant, choisis. Je deviens la lame de ton village et je protège les tiens comme mon clan. Ou je pars chercher l'homme au soleil brodé, seule, sur les routes."],
	], "choices": [["« Protège notre village. »", "join"], ["« Va, et reviens vivante. »", "voyage"]]},
	# ================================================================ ACTE V — Le serment des nains
	"kaia": {"pages": [
		["kaia", "Ouf ! Six jours de vol ! C'est toi, l'Éveillé ? Tu es plus petit que sur les chansons."],
		["hero", "Il y a des chansons sur moi ?"],
		["kaia", "Une ou deux. Pas très bonnes. Je suis Kaïa, messagère des cimes. Les harpies portent les nouvelles entre les peuples qui ne se parlent plus."],
		["kaia", "Et la nouvelle est mauvaise : les nains des montagnes sont assiégés. Des araignées géantes ont envahi leurs mines. Le maître forgeron Borin demande de l'aide."],
		["kaia", "Enfin... « demande » est un grand mot. Il a dit : « Si ce héros de pacotille veut du fer, qu'il vienne le chercher. » Ce sont des nains, que veux-tu."],
	]},
	"borin": {"pages": [
		["borin", "Hé ! Tu marches sur ma veine d'argent. Recule, et dis ce que tu veux avant que je te prenne pour un filon."],
		["hero", "Kaïa m'a dit que vos mines étaient envahies."],
		["borin", "Envahies ! Grouillantes, oui ! Des araignées grosses comme des chariots, sorties des profondeurs il y a un mois. Comme si quelque chose les avait chassées d'en bas."],
		["borin", "Chasse-les, et on parlera. Et ne compte pas sur moi pour te remercier, les nains ne remercient pas. Ils paient leurs dettes."],
	]},
	"wait_araignees": {"pages": [["borin", "Il en reste ! J'entends leurs pattes gratter la roche. Ça me donne des frissons jusqu'à la barbe."]]},
	"brunhild": {"pages": [
		["brunhild", "Alors c'est toi, le chasseur d'araignées. Je suis Brunhild, reine des nains sous la montagne. Borin est mon cousin, mon forgeron et ma migraine."],
		["brunhild", "Tu nous as rendu nos mines. Mais je vais te dire pourquoi les araignées sont remontées : au fond de la mine, nous avons trouvé ceci."],
		["brunhild", "Un cristal noir. Planté dans la roche comme une graine. Autour de lui, la pierre était morte, grise, pleine de Brume."],
		["brunhild", "Et nous avons vendu nos meilleurs cristaux à un seul acheteur, ces dernières années : l'Ordre de l'Aube Pure, les prêtres d'Hauterive. Ils payaient très cher. Beaucoup trop cher."],
		["hero", "Un soleil brodé sur des robes blanches... Kaede a vu ce symbole."],
		["brunhild", "Alors quelqu'un joue avec la Brume, et ce n'est pas un monstre. Garde les yeux ouverts, Éveillé. Et prouve à Borin que tu sais travailler : il ne jure que par ça."],
	]},
	"wait_borin_fer": {"pages": [["borin", "Dix lingots de fer. Minerai, four, patience. Je ne compte pas les excuses, seulement les lingots."]]},
	"borin_fer": {"pages": [
		["borin", "Voyons... Bonne coulée, pas de bulles. Tu as fondu ça toi-même ? Hmph. Il y a de l'espoir."],
		["borin", "Mon grand-père forgeait pour le Cœur d'Aube, tu sais. Les anneaux qui tenaient ses éclats, c'était lui. Les nains n'ont jamais oublié ce que la Brume nous a pris."],
		["borin", "Alors écoute bien, parce que je ne le dirai qu'une fois : voici du mithril brut. Fonds-le au four, deux morceaux pour un lingot. Avec assez de lingots, une enclume te fera des merveilles."],
		["borin", "Les grandes bêtes en gardent dans leur ventre, et les pioches de fer en arrachent parfois à la roche. Très rarement. Le mithril, ça se mérite."],
		["borin", "Et prends mon vieux marteau, et la Peau d'acier : le serment des nains. Maintenant, choisis : je viens forger dans ton village, ou je reste veiller sur mes montagnes avec ma reine ?"],
	], "choices": [["« Viens forger au village. »", "join"], ["« Veille sur ta montagne. »", "rester"]]},
	# ================================================================ ACTE VI — Les routes de Lysandre
	"lysandre": {"pages": [
		["lysandre", "Un client ! ... Ah non, un héros. Ça paie moins bien, en général."],
		["hero", "On dit que tu connais toutes les routes du royaume."],
		["lysandre", "Toutes, et même celles qui n'existent plus. Et je sais aussi ce qui marche dessus. Une horde, par exemple. Des orcs par centaines, affamés, qui dévorent tout sur leur passage."],
		["lysandre", "Elle finira par passer chez toi, héros. Tu veux savoir quand et par où ? Rien n'est gratuit : rapporte-moi cinq perles des eaux profondes."],
	]},
	"wait_perles": {"pages": [["lysandre", "Cinq perles, pas une de moins. Les eaux profondes en cachent : pêche, ou fouille les grottes englouties. Et fais vite, la horde ne t'attendra pas."]]},
	"perles": {"pages": [
		["lysandre", "Cinq perles, parfaites... Tu as plongé loin pour ça. Marché conclu."],
		["lysandre", "La horde s'appelle elle-même la Horde affamée. Leur terre a été rongée par la Brume : plus rien n'y pousse. Ils ne sont pas cruels, ils ont faim. Ce qui est pire."],
		["lysandre", "Prépare des gardes. Et en attendant, va voir la reine Zzar, au pays de la Ruche : si tu lui ouvres une route commerciale, tout le monde y gagnera. Surtout moi."],
		["lysandre", "Tiens, ma vieille cape de voyage : on ne se perd jamais avec. Et maintenant, je te propose ceci : je m'installe dans ton village, ou je te donne ma carte des anciens et une bourse pour la route."],
	], "choices": [["« Viens au village. »", "join"], ["« La carte et la bourse. »", "map"]]},
	"zzar": {"pages": [
		["zzar", "Zzz... Un mammifère. Deux bras, deux jambes, aucune antenne. Pathétique. Que veut-il à la Ruche ?"],
		["hero", "Ouvrir une route. Commercer, s'entraider. Lysandre m'envoie."],
		["zzar", "La lézarde. Elle vend nos gelées royales trois fois leur prix. Zzz. La Ruche n'a pas besoin de routes. La Ruche a besoin que les scorpions cessent de dévorer ses ouvrières."],
		["zzar", "Ils viennent en masse depuis que le désert est plein de Brume. Écrase-les, et la Ruche écoutera le mammifère."],
	]},
	"wait_scorpions": {"pages": [["zzar", "Zzz. Des scorpions, encore des scorpions. La Ruche compte. La Ruche attend."]]},
	"zzar_2": {"pages": [
		["zzar", "Les scorpions ont fui. Les ouvrières chantent. Zzz... La Ruche n'avait jamais chanté pour un mammifère."],
		["zzar", "La Ruche a un pacte à offrir : notre carapace. Quand le danger viendra, ta peau deviendra chitine, et les coups rebondiront sur toi."],
		["zzar", "Et ces écailles rouges. Nos ouvrières les ont trouvées dans le sable, près d'un vieux nid de dragon. La Ruche ne sait pas les travailler. Le mammifère, peut-être."],
		["zzar", "Va. La route est ouverte. Zzz... et dis à la lézarde que ses prix vont baisser."],
	]},
	# ================================================================ ACTE VII — La Horde affamée
	"kaia_2": {"pages": [
		["kaia", "Vite, vite, VITE ! La Horde ! Je l'ai vue depuis les nuages ! Elle marche droit sur ton village !"],
		["kaia", "Des centaines de feux... non, des dizaines, je ne sais plus, j'ai volé trop vite pour compter ! Mais ils seront là bientôt !"],
		["hero", "Préviens les gardes. Et Grik. Et Glou, qu'il cache la cuisine."],
		["kaia", "Glou a déjà mangé la moitié de la cuisine en apprenant la nouvelle. Le stress, a-t-il dit. Bonne chance, Éveillé !"],
	]},
	"gorvak": {"pages": [
		["gorvak", "... Tue-moi, si tu veux. Je suis Gorvak, fils du chef. Mon père est tombé devant tes murs. Il ne reste que moi et une poignée de ventres creux."],
		["hero", "Pourquoi avoir attaqué ? On aurait pu parler."],
		["gorvak", "Parler ? Quand tes enfants pleurent de faim depuis deux hivers, tu ne parles plus. Tu marches vers la première fumée de cuisine. La Brume a mangé nos champs, alors nous avons mangé le monde."],
		["gorvak", "Nous avons perdu. Prends la hache de mon père, elle est à toi par le droit du combat. Je ne demande rien pour moi. Mais les miens... Accueille-les, ou renvoie-les."],
	], "choices": [["« Vous êtes les bienvenus ici. »", "accueillir"], ["« Installez-vous plus loin, en paix. »", "exiler"]]},
	"maelle_cristal": {"pages": [
		["maelle", "Gorvak portait ça autour du cou ? Montre... Par les étoiles."],
		["maelle", "Un cristal de Brume. Taillé, poli, gravé. Regarde : un soleil, tout petit, sous la base. Le symbole de l'Ordre de l'Aube Pure."],
		["hero", "Ren avait le même. Et les nains en ont trouvé un planté dans leur mine."],
		["maelle", "Alors ce n'est pas un hasard. Quelqu'un sème la Brume. Dans les mines, dans les champs des orcs, dans l'âme d'un oni. Quelqu'un pousse les peuples à s'entre-dévorer."],
		["maelle", "Et ce quelqu'un porte un soleil. Je ne veux pas y croire... L'Ordre soigne les malades, à Hauterive. Mon propre maître y a étudié."],
		["maelle", "Gardons ça pour nous pour l'instant. D'abord, ces orcs ont faim. Un peuple affamé ne fait pas de pacte : il survit."],
	]},
	# ================================================================ ACTE VIII — Nourrir un peuple
	"wait_gorvak_ble": {"pages": [["gorvak", "Mon peuple a promis de ne plus piller. Mais une promesse ne remplit pas un ventre. Quinze bottes de blé, héros, et nous apprendrons à le cultiver nous-mêmes."]]},
	"gorvak_ble": {"pages": [
		["gorvak", "Du blé... Du vrai blé, doré, qui sent le soleil. Les petits ne savent même pas ce que c'est."],
		["gorvak", "Nous avons toujours pris ce que les autres faisaient pousser. Montre-nous comment on le fait pousser, et plus jamais un orc ne pillera un grenier."],
		["hero", "Les gobelins de Grik sont d'excellents fermiers. Ils vous apprendront."],
		["gorvak", "Des gobelins qui enseignent aux orcs... Mon père en mourrait une deuxième fois. ... Et il aurait tort."],
	]},
	"pip_eveil": {"pages": [
		["pip", "Regarde-moi ! REGARDE-MOI ! Je me suis réveillé ce matin et j'étais... GRAND !"],
		["grik", "Il a grandi de deux têtes pendant la nuit. Sa peau a foncé, ses yeux brillent. C'est un hobgobelin, maintenant. Comme dans les légendes."],
		["pip", "Orvane dit que c'est le Pacte ! Quand un peuple vit longtemps avec l'Éveillé, il change ! Il ÉVOLUE ! Les autres aussi vont changer, tu crois ?"],
		["hero", "Et moi, alors ? Je sens quelque chose... comme un écho de ta force."],
		["pip", "Bien sûr ! Un pacte, ça marche dans les deux sens ! Tu nous fais grandir, on te fait grandir ! C'est le meilleur marché du monde, même Lysandre ne fait pas mieux !"],
		["grik", "Et pour fêter ça, un festin ! Un vrai ! Tous les peuples autour de la même table : gobelins, loups, orcs, nains, tout le monde ! Il me faut du pain. Beaucoup de pain."],
	]},
	"wait_grik_festin": {"pages": [["grik", "Dix pains ! Il faut que tout le monde mange, même Glou. Surtout Glou, sinon il mange la table."]]},
	"grik_festin": {"pages": [
		["grik", "Dix pains ! Magnifique ! Ce soir, gobelins, orcs, nains et loups mangeront ensemble. Mon grand-père ne me croirait pas."],
		["gorvak", "Les orcs ont apporté de la viande. Les loups d'Ulric l'ont chassée avec nous. C'est... étrange. Bon, mais étrange."],
		["glou", "FESTIN ! Glou aime festin ! Glou aime tout le monde ! Glou mange le reste !"],
		["grik", "Regarde, là-bas, à l'orée du village. Quelqu'un est venu, attiré par les chants. Une dryade ! Les dryades ne sortent jamais des forêts..."],
	]},
	"sylve": {"pages": [
		["sylve", "Pardonnez-moi d'interrompre la fête. Je suis Sylve, la voix des arbres de ce pays. Les racines m'ont apporté vos chants jusqu'au fond de la forêt."],
		["sylve", "Cela faisait trois siècles que la terre n'avait pas entendu des peuples différents chanter ensemble. Elle en a frissonné de joie."],
		["hero", "Trois siècles... Depuis que le Cœur d'Aube a été brisé ?"],
		["sylve", "Oui. Avant, un autre Éveillé faisait chanter les peuples comme toi. Les arbres se souviennent de sa voix. Elle ressemblait beaucoup à la tienne."],
		["hero", "Un autre Éveillé ? Qu'est-il devenu ?"],
		["sylve", "Les arbres n'aiment pas en parler. Ils se taisent quand je leur demande. Mais prends le Pacte des Racines : quand tu seras blessé, la terre te soignera, toi et les tiens. Et je resterai ici, si vous voulez bien de moi."],
	]},
	# ================================================================ ACTE IX — La couronne d'Hauterive
	"alderic": {"pages": [
		["alderic", "Halte ! Au nom du roi d'Hauterive ! ... Tu es donc celui qui commande à des gobelins, à des orcs, à une dryade et à un slime."],
		["hero", "Je ne commande personne. Nous vivons ensemble."],
		["alderic", "Ensemble. Le roi n'aime pas ce mot quand il s'applique aux monstres. Je suis Aldéric, chevalier d'Hauterive. On m'a envoyé juger si ton village est une menace."],
		["alderic", "Je ne juge pas un homme sur ses amis, mais sur ses actes. Une bête ravage les villages frontaliers depuis ce donjon. Abats-la, et je saurai ce que tu vaux."],
	]},
	"wait_bete": {"pages": [["alderic", "La bête est toujours en vie. Son donjon est tout près : carré rouge sur ta carte."]]},
	"alderic_2": {"pages": [
		["alderic", "Tu l'as fait... Je l'ai vue tomber de loin, la Brume s'est dissipée au-dessus du donjon."],
		["alderic", "Le roi Edmond est en voyage dans le royaume. Il faut que tu le rencontres toi-même : ma parole ne suffira pas contre celle de l'Ordre."],
		["hero", "L'Ordre de l'Aube Pure ? Que pensent-ils de nous ?"],
		["alderic", "Que vous êtes une abomination. Le Grand Inquisiteur Morvain le répète à la cour tous les jours. Moi, je n'ai vu qu'un village qui rit plus que ma caserne."],
		["alderic", "Choisis : je reste à ton service et je défends ton village, ou je rentre plaider ta cause à la cour, et je te confie la Lame d'Aube, l'épée de mon ordre."],
	], "choices": [["« Rejoins mon village. »", "join"], ["« Plaide notre cause, confie-moi ta lame. »", "blade"]]},
	"edmond": {"pages": [
		["edmond", "Approche. Non, pas à genoux, je déteste ça. Je suis Edmond, roi d'Hauterive. Et tu es le « roi des monstres » dont mon Inquisiteur me parle à chaque repas."],
		["hero", "Je ne suis roi de rien. Juste quelqu'un qui aide ceux qui ont besoin d'aide."],
		["edmond", "C'est exactement ce que dirait un roi habile. ... Pardonne-moi, trente ans de cour rendent méfiant."],
		["edmond", "Aldéric t'a vu à l'œuvre, et Aldéric ne ment jamais : c'est son plus grand défaut. Je suis prêt à signer un traité. Mais la cour voudra un geste. De l'or, pour prouver ta bonne foi."],
		["edmond", "Trois lingots d'or. Ce n'est rien pour un royaume, mais c'est un symbole. Et les symboles gouvernent les hommes plus sûrement que les épées."],
	]},
	"wait_traite": {"pages": [["edmond", "Trois lingots d'or, mon ami. La cour aime ce qui brille. Moi, j'aime ce qui dure."]]},
	"traite": {"pages": [
		["edmond", "Trois lingots. Parfait. Voilà, je signe : Hauterive et ton peuple sont alliés, pour le meilleur et pour les impôts."],
		["edmond", "Prends ce bouclier, il porte le soleil d'Hauterive. Quiconque le verra saura que tu es sous ma protection."],
		["edmond", "Un dernier mot. Morvain va venir te voir. Il a insisté pour « bénir » notre alliance. Je ne l'ai jamais aimé... mais c'est lui qui a guéri ma fille de la fièvre de Brume. Je lui dois beaucoup."],
		["edmond", "Sois courtois avec lui. Et sois prudent."],
	]},
	# ================================================================ ACTE X — Le Grand Inquisiteur
	"morvain": {"pages": [
		["morvain", "Paix sur toi, enfant. Je suis Morvain, Grand Inquisiteur de l'Ordre de l'Aube Pure. Le roi m'envoie bénir votre alliance."],
		["morvain", "Nous avons longtemps cru que les monstres étaient la Brume elle-même. Tu nous as prouvé le contraire. L'Ordre te tend la main."],
		["hero", "Que veut l'Ordre en échange ?"],
		["morvain", "Seulement aider. Nos textes disent que les éclats du Cœur d'Aube doivent être purifiés avant d'être réunis. Rassemble-en quatre, et je les bénirai moi-même."],
		["morvain", "Ta... ta nation grandit vite, enfant. Il serait dommage qu'elle grandisse de travers."],
	], "choices": [["« Merci, Inquisiteur. »", "confiance"], ["« Je garderai un œil sur vous. »", "mefiance"]]},
	"orvane_doute": {"pages": [
		["orvane", "Ce prêtre... Quand il est passé devant mon cristal, mes chaînes ont chanté. Pas de douleur. De reconnaissance."],
		["hero", "Tes chaînes le reconnaissent ? Tu le connais ?"],
		["orvane", "Non. Mais je connais l'odeur de ce qu'il porte sous sa robe. Un cristal de Brume, bien plus gros que ceux que tu as trouvés. Et plein. Plein à ras bord."],
		["orvane", "Rassemble les éclats, puisqu'il le faut. Mais ne les lui donne jamais. Jamais, tu m'entends ?"],
		["hero", "Orvane... qui t'a enchaîné, exactement ?"],
		["orvane", "... Une autre fois, revenant. Une autre fois."],
	]},
	"lysandre_secret": {"pages": [
		["lysandre", "Ferme la porte. Personne ne doit entendre. ... Je te dois la vérité, et ça ne me plaît pas du tout."],
		["lysandre", "Depuis que je te connais, je vends tout ce que je sais de toi à Morvain. Tes alliés, tes routes, tes éclats. Il paie en or, et l'or, je ne sais pas dire non."],
		["hero", "Lysandre... Pourquoi me le dire maintenant ?"],
		["lysandre", "Parce qu'hier, il m'a demandé l'emplacement exact de ta salle aux éclats, et le nombre de tes gardes. Et il souriait. On ne sourit pas comme ça pour une bénédiction."],
		["lysandre", "Je suis une marchande, pas une traîtresse. Enfin, plus maintenant. Il prépare quelque chose, héros. Quelque chose de gros. Ne le laisse pas approcher de tes éclats."],
	]},
	"maelle_3": {"pages": [
		["maelle", "Quatre éclats ! Regarde comme ils brillent quand on les rapproche... Le Cœur veut se reformer."],
		["maelle", "Mais j'ai relu tous mes textes, cette nuit. Il n'existe aucune « purification ». Les éclats sont purs, ils sont la lumière même. Morvain ment."],
		["hero", "Lysandre m'a tout avoué. Il l'a payée pour m'espionner."],
		["maelle", "Alors il faut... Attends. Tu entends ce cor ? Ça vient de la forêt. Ce sont ses templiers, en armure blanche... Leurs yeux ! Leurs yeux sont vides !"],
		["maelle", "Ils marchent sur le village ! Aux armes ! AUX ARMES !"],
	]},
	# ================================================================ ACTE XI — La trahison
	"enlevement": {"pages": [
		["grik", "Tu es vivant ! Les templiers ont reculé, les gardes ont tenu, Glou en a avalé deux !"],
		["grik", "Mais... pendant la bataille, des soldats sont passés par derrière. Ils sont allés droit à la maison de Maëlle."],
		["hero", "Maëlle ! Où est-elle ?"],
		["grik", "Partie. Emmenée. Il ne restait que ses lunettes cassées, et ce message cloué sur la porte : « Qu'il apporte les éclats, ou l'elfe rejoindra la Brume. — M. »"],
		["grik", "Les éclats sont toujours là, je les ai cachés dans ma marmite. Personne ne fouille la marmite d'un vieux gobelin. Va voir Orvane. Il sait des choses, j'en suis sûr."],
	]},
	"orvane_3": {"pages": [
		["orvane", "Ils ont pris l'elfe. Je l'ai senti. Et Morvain est passé devant mon cristal en riant."],
		["orvane", "Morvain n'est pas un prêtre, c'est un héraut du Seigneur de la Brume. Il y a trois cents ans, c'est un homme comme lui qui a ouvert les portes du Sanctuaire."],
		["hero", "Qu'est-ce qu'il veut faire avec les éclats ?"],
		["orvane", "Les rendre à son maître. Avec le Cœur complet, le Seigneur de la Brume se relèverait entier. Et cette fois, personne ne pourrait l'arrêter. Pas même moi."],
		["orvane", "Ne donne rien. Reprends l'elfe par la force. La harpie vole plus vite que n'importe quel ravisseur : elle les a sûrement suivis."],
	]},
	"kaia_3": {"pages": [
		["kaia", "Je les ai suivis ! Toute la nuit, au-dessus des nuages ! Ils ont emmené Maëlle dans un repaire au loin, gardé par des morts qui marchent."],
		["kaia", "Mais il y a autre chose. Sur la route, j'ai vu un château noir. Et une femme sur les remparts, qui regardait le repaire de Morvain avec des yeux rouges comme des braises."],
		["kaia", "Elle m'a vue. Elle m'a souri. Et elle a dit, sans crier, mais je l'ai entendue quand même : « Dis à l'Éveillé que je l'attends. »"],
		["hero", "Une vampire..."],
		["kaia", "La reine de la Nuit, Séléné. On raconte qu'elle a trois cents ans. Pile l'âge de la Brume. Fais attention à toi."],
	]},
	"selene": {"pages": [
		["selene", "Te voilà enfin. Tu es plus jeune que je l'imaginais. Il était plus jeune aussi, la première fois que je l'ai vu."],
		["hero", "Qui ça, « il » ?"],
		["selene", "Chaque chose en son temps, petit Éveillé. Je suis Séléné, reine de la Nuit. Et je chasse Morvain depuis cinquante ans. Ses maîtres et moi avons une vieille querelle."],
		["selene", "Son repaire est gardé par des templiers morts. Je ne peux pas y entrer : il a béni le seuil contre les vampires. Mais toi, tu peux."],
		["selene", "Alors je te propose un pacte de circonstance : tu reprends ton elfe, tu abats Morvain, et je te dirai ce que tu dois savoir. Ce qu'Orvane ne t'a jamais dit."],
	], "choices": [["« Marché conclu. »", "alliance"], ["« Je le fais pour Maëlle, pas pour toi. »", "mefiance"]]},
	# ================================================================ ACTE XII — Le Parjure
	"wait_templiers": {"pages": [["morvain", "Tu veux me parler, enfant ? Passe d'abord sur le corps de mes templiers. Ils ne sentent plus la douleur, eux."]]},
	"duel_morvain": {"pages": [
		["morvain", "Te voilà, l'Éveillé. Sans les éclats, je suppose. Quel dommage. L'elfe aurait fait une si jolie Brume."],
		["hero", "Libère-la. Tout de suite."],
		["morvain", "Sais-tu seulement qui tu sers ? Ce vieux fou d'Orvane t'a menti depuis le premier jour. Demande-lui qui était le premier Éveillé. Demande-lui qui il a TRAHI !"],
		["morvain", "Mon maître t'aurait laissé régner sur tes petits monstres, à genoux dans la Brume. Mais puisque tu refuses... Regarde bien mon vrai visage, enfant !"],
	]},
	"maelle_sauvee": {"pages": [
		["maelle", "{hero} ! Tu es venu... Détache-moi, vite, ces chaînes me brûlent."],
		["maelle", "J'ai entendu Morvain parler à son cristal, toutes les nuits. Il parlait à quelqu'un. À son maître. Et il l'appelait par son nom : Caël."],
		["hero", "Caël ? Qui est-ce ?"],
		["maelle", "Dans les plus vieux textes de l'Ordre, Caël est le nom du premier roi. Celui qui a fondé le royaume, il y a trois siècles. On dit qu'il venait « d'un autre monde »."],
		["maelle", "Tu comprends ce que ça veut dire ? Le Seigneur de la Brume... c'était un Éveillé. Comme toi."],
	]},
	"selene_2": {"pages": [
		["selene", "Morvain est tombé. Je l'ai senti mourir d'ici, comme un nœud qui se défait. Merci, petit Éveillé. Voici ta vérité."],
		["selene", "Il y a trois cents ans, un jeune homme est tombé du ciel dans un soir de pluie. Il s'appelait Caël. Il parlait aux esprits, il faisait des pactes, il faisait chanter les peuples. Comme toi."],
		["selene", "Il a fondé le royaume. Il a allumé les obélisques. Et il m'a aimée. Moi, une vampire. Nous devions nous marier au printemps."],
		["selene", "Mais Caël avait peur de mourir. Une seconde fois. Il a voulu que le Cœur d'Aube le rende éternel en dévorant l'âme de tous ceux qui avaient fait un pacte avec lui. Sa lumière est devenue la Brume."],
		["selene", "Prends ceci : la Brume inversée. Le seul pouvoir que j'aie volé à Caël avant qu'il ne tombe. Et va demander à Orvane pourquoi il a brisé le Cœur. Il était le meilleur ami de Caël. Son premier pacte."],
	]},
	"orvane_verite": {"pages": [
		["hero", "Caël. Le premier Éveillé. Ton premier pacte. Tu m'as menti, Orvane."],
		["orvane", "... Oui. Je t'ai menti. Parce que j'avais peur que tu deviennes comme lui. Et parce que j'avais honte."],
		["orvane", "Caël était mon ami. Mon frère. Quand il a voulu dévorer toutes les âmes liées par ses pactes, j'étais la première. J'ai compris avant les autres."],
		["orvane", "Alors j'ai brisé le Cœur de l'intérieur, pour que sa lumière ne puisse jamais être entière. La moitié de Caël est devenue la Brume. L'autre moitié... m'a enchaîné ici. Pour que je le regarde revenir, siècle après siècle."],
		["hero", "Et moi ? Pourquoi suis-je ici ?"],
		["orvane", "Je ne sais pas. Peut-être que le monde a besoin d'un Éveillé qui choisisse autrement. Tu peux partir, maintenant que tu sais. Je ne t'en voudrai pas."],
		["hero", "Je reste. On a fait un pacte, toi et moi. Et moi, je tiens mes promesses."],
		["orvane", "... Merci. Alors bâtis une salle du trône, et réunis tous les peuples. Cette fois, ce n'est pas un roi qui affrontera la Brume. C'est une nation."],
	]},
	# ================================================================ ACTE XIII — Le conseil des pactes
	"conseil": {"pages": [
		["grik", "Hum hum ! Silence, s'il vous plaît ! Le premier conseil des pactes est ouvert ! ... J'ai toujours rêvé de dire ça."],
		["grik", "Gobelins, loups, fées, oni, nains, hommes-lézards, insectes, orcs, dryades, elfes, et même une vampire... Il y a un an, la moitié de ces peuples se mangeait entre eux."],
		["hero", "Caël, le Seigneur de la Brume, va se réveiller. Il nous faut tous les éclats du Cœur d'Aube, et toutes les grandes bêtes sont encore debout."],
		["grik", "Alors chaque peuple enverra ses meilleurs guerriers. Le conseil a voté, c'est décidé ! ... C'est bien comme ça qu'on fait un conseil, hein ?"],
		["grik", "Ah, et un invité spécial a demandé à parler. Il est arrivé ce matin avec une escorte de chevaliers. Il a une couronne. Une vraie."],
	]},
	"edmond_2": {"pages": [
		["edmond", "Mes amis. Je viens vous demander pardon."],
		["edmond", "L'homme qui a enlevé votre érudite, qui a semé la Brume dans les mines et dans les champs, qui a empoisonné le frère d'une oni... il dormait sous mon toit. Il a guéri ma fille, et je l'ai laissé faire."],
		["edmond", "L'Ordre de l'Aube Pure est dissous. Ses biens iront aux peuples qu'il a fait souffrir. Et Hauterive se joint au conseil, si le conseil veut bien de nous."],
		["hero", "Il y a de la place pour tout le monde, Edmond. C'est le principe."],
		["edmond", "Alors écoute : mes archives parlent d'un dernier dragonide, Vharok, qui garde le nid des anciens dragons. Ses écailles valent toutes les armures du royaume. Mais il hait les humains... et il n'a pas tort."],
	]},
	"vharok": {"pages": [
		["vharok", "Un sang-chaud. Sur MON territoire. Tu as trois battements de cœur pour m'expliquer pourquoi je ne devrais pas te réduire en cendres."],
		["hero", "Parce que je viens avec le conseil des pactes. Et parce que quelque chose profane le nid de tes ancêtres."],
		["vharok", "... Tu le sais ? Une bête de Brume a creusé son antre sous le nid. Elle dévore les œufs pétrifiés, les derniers espoirs de mon peuple."],
		["vharok", "Caël aussi était venu, il y a trois cents ans. Il avait promis de protéger les dragons. Puis il a lâché la Brume, et mes ancêtres sont morts les premiers."],
		["vharok", "Je ne crois plus aux promesses des Éveillés. Je crois aux actes. Tue la bête, et je t'écouterai."],
	]},
	"wait_vharok_bete": {"pages": [["vharok", "La bête respire encore. J'entends ses griffes sur les œufs. Le donjon, sang-chaud. Maintenant."]]},
	# ================================================================ ACTE XIV — Les dragons et l'ange
	"vharok_2": {"pages": [
		["vharok", "Elle est morte. Et les œufs... un des œufs est tiède. TIÈDE. Trois siècles, et un œuf de dragon se réchauffe."],
		["vharok", "Tu n'es pas Caël. Caël promettait. Toi, tu fais. C'est une différence que même un vieux dragonide peut comprendre."],
		["vharok", "Prends ces écailles, et ce sang de démon que j'ai arraché aux gardiens de la bête. Forge-toi quelque chose qui ne brûlera pas. Et prends le souffle de mes ancêtres."],
		["vharok", "Rassemble le Cœur, sang-chaud. Et quand tu affronteras Caël, souffle-lui ce feu au visage de ma part."],
	]},
	"aurele": {"pages": [
		["aurele", "Éveillé. Je suis Aurèle, Séraphin du Ciel. Je suis descendue parce que le Ciel a peur."],
		["aurele", "Il y a trois cents ans, un Éveillé a rassemblé le Cœur d'Aube, et le monde a failli mourir. Aujourd'hui, un autre Éveillé rassemble le Cœur. Le Ciel a déjà vu cette histoire."],
		["hero", "Je ne suis pas Caël."],
		["aurele", "Caël non plus n'était pas Caël, au début. Le Ciel m'a ordonné de détruire les éclats. Tous. Pour toujours. La Brume resterait, mais aucun Éveillé ne pourrait plus jamais devenir un dieu."],
		["aurele", "Mais je ne suis pas qu'un ordre du Ciel. Je veux voir ta volonté de mes propres yeux. Lame contre lame. Si ton cœur tremble, je détruirai les éclats. S'il tient... nous verrons."],
	]},
	"duel_aurele": {"pages": [
		["aurele", "Prépare-toi. Je ne retiendrai pas mes coups : la Brume ne retiendra pas les siens."],
		["hero", "Je suis prêt."],
		["aurele", "Alors montre-moi pourquoi tu te bats, Éveillé !"],
	]},
	"aurele_2": {"pages": [
		["aurele", "... Tu as gagné. Mais ce n'est pas ça qui compte. Pendant tout le combat, tu n'as jamais cherché à me tuer. Tu voulais seulement me convaincre."],
		["aurele", "Caël, lui, m'aurait tuée sans hésiter. C'est ce qu'il a fait à ma sœur, il y a trois cents ans."],
		["aurele", "Je désobéis au Ciel. Garde les éclats. Et prends mes ailes : tant que tu te battras pour les autres, tu ne tomberas pas."],
		["aurele", "Prends aussi ce cristal d'aube, né du premier Cœur. Il reste très peu de ces cristaux au monde. Avec de l'orichalque, un forgeron pourrait en faire une lame capable de trancher la Brume elle-même."],
	]},
	# ================================================================ ACTE XV — Le Cœur d'Aube
	"wait_coeur": {"pages": [["maelle", "Il me faut un temple pour reformer le Cœur : une pièce fermée avec un autel et deux bougeoirs."]]},
	"coeur": {"pages": [
		["maelle", "Tous les éclats... et ce temple. Pose-les sur l'autel, là. N'aie pas peur."],
		["maelle", "... Le Cœur d'Aube. Je n'aurais jamais cru le voir de mes yeux. Il bat, tu entends ? Comme un vrai cœur."],
		["maelle", "Mais il bat à moitié. L'autre moitié, c'est la Brume. C'est Caël. Tant qu'il existera, le Cœur ne sera jamais entier."],
		["maelle", "Porte-le d'abord à Orvane. Trois cents ans de chaînes, ça suffit. Ensuite, il faudra affronter Caël au Sanctuaire de l'Éveil, là où tout a commencé. Je l'ai marqué sur ta carte."],
	]},
	"orvane_libre": {"pages": [
		["orvane", "Je le sens... Le Cœur. Approche-le du cristal, doucement."],
		["orvane", "... Oh. Oh, le vent. J'avais oublié le vent. Et l'odeur de l'herbe après la pluie. Et le poids de mes propres branches."],
		["glou", "CAILLOU-QUI-PARLE EST SORTI ! Il est... grand ! Très grand ! Glou peut monter dessus ?"],
		["orvane", "Monte, petit. Tu l'as bien mérité, depuis le temps que tu me tiens compagnie."],
		["orvane", "Je suis libre. Grâce à un revenant têtu d'un autre monde. Tu as tenu ta part du pacte. Prends mes chaînes : elles sont brisées, mais elles savent encore serrer. Retourne-les contre la Brume."],
		["orvane", "Maintenant, prépare l'armée des pactes. Et forge-toi une arme digne de ce combat. Caël ne sera pas une grande bête comme les autres : il a été l'un de nous."],
	]},
	"selene_3": {"pages": [
		["selene", "Demain, tu affronteras Caël. Je suis venue... je ne sais pas pourquoi je suis venue."],
		["hero", "Tu l'aimes encore."],
		["selene", "Après trois siècles ? ... Oui. Non. J'aime celui qu'il était, le jeune homme tombé du ciel un soir de pluie. Celui qui est au Sanctuaire n'est plus lui."],
		["selene", "Quand tu l'auras vaincu, son âme restera. Une âme d'Éveillé ne meurt pas facilement. Tu devras choisir : la libérer, ou la prendre en toi."],
		["selene", "Je ne te dirai pas quoi faire. Mais... si tu peux, dis-lui que je l'ai attendu."],
	], "choices": [["« Je lui dirai. »", "promesse"], ["« Viens le lui dire toi-même. »", "ensemble"]]},
	# ================================================================ ACTE XVI — L'Éveil
	"wait_veilleurs": {"pages": [["orvane", "Les Veilleurs gardent encore le cercle. Brise-les, revenant, et le Sanctuaire s'ouvrira."]]},
	"cael": {"pages": [
		["cael", "... Tu m'as vaincu. Toi, un Éveillé de plus. Tombé du ciel un soir de pluie, je parie."],
		["hero", "Un soir de pluie. Des phares. Un choc."],
		["cael", "Moi, c'était un train. Je m'appelais autrement, là-bas. Je rangeais des boîtes dans un entrepôt, douze heures par jour. Personne ne se souvenait de mon nom."],
		["cael", "Ici, tout le monde le chantait. J'avais des amis, un royaume, une fiancée. Et j'ai eu si peur de tout perdre une deuxième fois que j'ai tout détruit moi-même. C'est drôle, non ?"],
		["hero", "Séléné m'a demandé de te dire qu'elle t'avait attendu. Trois cents ans."],
		["cael", "... Séléné. Ma Séléné. Alors je n'ai pas tout détruit. ... Ton âme est vaste, petit Éveillé. Tu peux me libérer, ou me prendre en toi. Mon pouvoir sera tien dans les deux cas. Choisis."],
	], "choices": [["« Va en paix, Caël. »", "liberer"], ["« Je porterai ton âme avec moi. »", "absorber"]]},
	"epilogue": {"pages": [
		["orvane", "Regarde les obélisques : ils brillent tous, même au loin. La Brume se retire des vallées, les champs des orcs reverdissent déjà. Et le Cœur bat. Entier, cette fois."],
		["maelle", "J'ai écrit toute ton histoire, depuis le cristal jusqu'au Sanctuaire. Personne ne me croira, mais c'est la plus belle chose que j'aie jamais écrite."],
		["hero", "Dans ma première vie, je courais sans jamais arriver nulle part. Ici, j'ai enfin trouvé où j'allais."],
		["orvane", "Alors il faut donner un nom à ce lieu. Les peuples du conseil ont voté : c'est toi qui choisis. Et tu porteras cette couronne : une gemme pour chaque peuple. Comment s'appellera notre nation ?"],
	], "choices": [["« Le Royaume de l'Aube. »", "aube"], ["« La Fédération des Pactes. »", "pactes"], ["« Les Terres d'Orvane. »", "orvane"]]},
	"fondation": {"pages": [
		["grik", "Mesdames, messieurs, gobelins, orcs, nains, loups, fées, dragons et slimes ! La fête de la fondation commence !"],
		["pip", "J'ai grandi, j'ai chassé, j'ai même appris à lire avec Maëlle ! Et maintenant, je suis le chef des éclaireurs de toute la nation !"],
		["glou", "Glou a cuisiné ! Glou a cuisiné TOUT ! ... Glou a goûté un peu. Beaucoup. Mais il en reste !"],
		["grik", "Il y a un an, j'étais un vieux gobelin qui attendait de mourir sous un buisson. Aujourd'hui, je suis le doyen du conseil d'une nation. Tout ça grâce à un étranger qui s'est arrêté pour écouter."],
		["hero", "Grâce à nous tous, Grik. Un pacte, ça marche dans les deux sens."],
		["grik", "Bien dit ! Alors levez vos chopes ! À l'Éveillé ! Aux pactes ! Et à tout ce qu'il nous reste à construire !"],
	]},
	# ================================================================ phrases du quotidien
	"orvane_idle": {"pages": [["orvane", "Ton journal (O) garde la trace de notre histoire. Et ton arbre de talents (T), celle de nos pactes."]]},
	"glou_idle": {"pages": [["glou", "Blup ! Glou garde la cuisine. Glou mange PAS la cuisine. ... Un peu."]]},
	"grik_idle": {"pages": [["grik", "Les gobelins n'oublient jamais une dette ! Tu veux des baies ? Il nous en reste plein, maintenant."]]},
	"pip_idle": {"pages": [["pip", "Je surveille les pistes ! Si un monstre approche, je le saurai avant lui."]]},
	"ulric_idle": {"pages": [["ulric", "La meute chasse avec les gobelins, maintenant. Les cerfs reviennent dans les bois. Hurle, et nous viendrons."]]},
	"maelle_idle": {"pages": [["maelle", "Les textes anciens ne disent pas tout... mais je te suis. Ton journal (O) garde la trace de ta quête."]]},
	"liora_idle": {"pages": [["liora", "Hi hi ! Tu n'aurais pas un petit pain, par hasard ? Non ? Dommage."]]},
	"kaede_idle": {"pages": [["kaede", "Ma lame est affûtée. Montre-moi qui trancher."]]},
	"kaia_idle": {"pages": [["kaia", "Pas de nouvelles, bonnes nouvelles ! Enfin, en général."]]},
	"borin_idle": {"pages": [["borin", "Le fer ne ment pas. Le mithril non plus. Les gens, si. Surtout les prêtres."]]},
	"brunhild_idle": {"pages": [["brunhild", "Les mines chantent de nouveau. Merci, Éveillé. Borin ne te le dira pas, alors je te le dis."]]},
	"lysandre_idle": {"pages": [["lysandre", "Les affaires reprennent ! Et cette fois, honnêtement. Presque."]]},
	"zzar_idle": {"pages": [["zzar", "Zzz. La Ruche prospère. La Ruche tolère le mammifère."]]},
	"gorvak_idle": {"pages": [["gorvak", "Mes guerriers apprennent à labourer. Ils sont nuls. Mais ils rient, et ça, je ne l'avais plus entendu."]]},
	"sylve_idle": {"pages": [["sylve", "Les arbres chantent ton nom, Éveillé. Doucement, mais ils le chantent."]]},
	"alderic_idle": {"pages": [["alderic", "Ma lame est à ton service, Éveillé."]]},
	"edmond_idle": {"pages": [["edmond", "Un roi qui écoute les gobelins... Mon père en rirait. Moi, je trouve que ça gouverne plutôt bien."]]},
	"morvain_idle": {"pages": [["morvain", "Quatre éclats, enfant. N'oublie pas. Quatre, et je les purifierai."]]},
	"selene_idle": {"pages": [["selene", "La nuit est belle, ce soir. Elle l'était aussi, il y a trois cents ans."]]},
	"vharok_idle": {"pages": [["vharok", "L'œuf est toujours tiède. Je le veille, sang-chaud. Je le veille."]]},
	"aurele_idle": {"pages": [["aurele", "Le Ciel observe. Moi, j'ai choisi de croire."]]},
	"cael_idle": {"pages": [["cael", "..."]]},
}
